services:
  - name: webservice1
    type: web
    runtime: docker
    plan: free
    repo: https://github.com/ValeriaMirza/WebProxyS
    branch: main
    ports:
      - 5001
    dockerfilePath: Dockerfile

  - name: webservice2
    type: web
    runtime: docker
    plan: free
    repo: https://github.com/ValeriaMirza/WebProxyS
    branch: main
    ports:
      - 5002
    dockerfilePath: Dockerfile

  - name: nginx
    type: web
    runtime: docker
    plan: free
    repo: https://github.com/ValeriaMirza/WebProxyS
    branch: main
    ports:
      - 80
    dockerfilePath: Dockerfile
